services:
  community-service:
    build: .
    ports:
      - "8091:8091"
    environment:
      spring.data.mongodb.uri:      mongodb://root:example@mongo:27017/communitiesDb?authSource=admin
      spring.data.mongodb.database: communitiesDb
      thread-service.url: http://app:8090/threads
    depends_on:
      - mongo
      - mongo-express
    volumes:
      - ../volumes/logs/community-service:/app/logs
    networks:
      - my_shared_net

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE:       communitiesDb
    ports:
      - "27018:27018"
    networks:
      - my_shared_net


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL:           mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH:             false
    depends_on:
      - mongo
    networks:
      - my_shared_net

networks:
  my_shared_net:
    external: true