server:
  port: 8090

spring:
  application:
    name: ThreadService
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

