services:
  #  APPS
  thread-service:
    build: .
    ports:
      - "8090:8090"
    environment:
      spring.data.mongodb.uri: mongodb://root:example@mongo:27017/threadDb?authSource=admin
      spring.data.mongodb.database: threadDb
    volumes:
      - ../volumes/logs/thread-service:/app/logs
    depends_on:
      - mongo
      - mongo-express
      - redis_cache
    networks:
      - my_shared_net



  # MongoDB
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: threadDb
    ports:
      - "27017:27017"
    networks:
      - my_shared_net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9001:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - my_shared_net
  redis_cache:
    image: redis:latest
    container_name: redisCache
    ports:
      - "6379:6379"
    networks:
      - my_shared_net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight
    ports:
      - "5540:5540"
    restart: always
    networks:
      - my_shared_net

networks:
  my_shared_net:
    external: true

