server:
  port: 8091
  error:
    include-message: always

spring:
  application:
    name: CommunitiesService
  profiles:
    active: dev

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
