apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: redditclone/user-service:latest
          ports:
            - containerPort: 8080
          env:
            # Load the "dev" profile so Spring reads dev.yml overrides
            - name: SPRING_PROFILES_ACTIVE
              value: dev

            # add app url
            - name: SERVICE_URL
              value: http://localhost:8081/api/user

            # Point at your Postgres headless Service:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-user:5432/user_service

            # Pull username & password from the Secret:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            # JWT Configuration
            - name: JWT_EXPIRATION_MS
              value: "6000000000"

            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"

            # Redis
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
