name: notification-service CI/CD

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
    paths:
      - 'notification-service/**'
      - '.github/workflows/notification-service-ci-cd.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'notification-service/**'
      - '.github/workflows/notification-service-ci-cd.yml'
  workflow_run:
    workflows:
      - "user-service CI/CD"
    types:
      - completed

jobs:
  ci:
    uses: ./.github/workflows/ci-java-maven.yml
    with:
      branch: ${{ github.ref }}
      service-dir: 'notification-service'
    secrets: inherit

  docker:
    needs: ci
    uses: ./.github/workflows/cd-docker-push.yml
    with:
      artifact-name: 'packaged-artifact'
      service-dir: 'notification-service'
      image-name: 'notification-service'
    secrets: inherit
