name: thread-service CI/CD

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
    paths:
      - 'thread-service/**'
      - '.github/workflows/thread-service-ci-cd.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'thread-service/**'
      - '.github/workflows/thread-service-ci-cd.yml'

jobs:
  ci:
    uses: ./.github/workflows/ci-java-maven.yml
    with:
      branch: ${{ github.ref }}
      service-dir: 'thread-service'
    secrets: inherit

  docker:
    needs: ci
    uses: ./.github/workflows/cd-docker-push.yml
    with:
      artifact-name: 'packaged-artifact'
      service-dir: 'thread-service'
      image-name: 'thread-service'
    secrets: inherit
